# if given, will override the device setting in gym.
env:
  numEnvs: 64
  envSpacing: 1.5
  episodeLength: 500
  enableDebugVis: True

  startPositionNoise: 0.1
  startRotationNoise: 0.0

  aggregateMode: 3

  actionScale: 1.0
  dofVelocityScale: 0.1
  distRewardScale: 0.5
  rotRewardScale: 0.02
  openRewardScale: 4.0
  actionPenaltyScale: 0.01

  asset:
    assetRoot: "../assets"
    assetFileNameUR3: "urdf/ur3_description/robot/ur3_robotiq85_gripper.urdf"
    assetFileNameBottle: "urdf/objects/bottle.urdf"

expert:
  num_total_frames: 100000

sim:
  substeps: 1
  physx:
    num_threads: 4
    solver_type: 1  # 0: pgs, 1: tgs
    num_position_iterations: 30 # 12
    num_velocity_iterations: 1
    contact_offset: 0.008 # 0.005
    rest_offset: 0.0
    bounce_threshold_velocity: 0.2
    max_depenetration_velocity: 10000.0
    default_buffer_size_multiplier: 5.0
    always_use_articulations: False

  flex:
    num_outer_iterations: 4
    num_inner_iterations: 15
    warm_start: 0.8
    relaxation: 0.75

task:
  randomize: False
